- name: Download pubkey from GitHub and placed as authorized_keys
  get_url: url=https://github.com/{{ item }}.keys dest=/tmp/{{ item }}.github_authorized_keys
  with_items: "{{ github_users }}"

- name: Create authorized_keys for root from the file that just downloaded
  authorized_key: user=root key="{{ lookup('file', item) }}"
  with_fileglob:
    - /tmp/*.github_authorized_keys
  register: add_authorized_keys

- name: Only allow ssh access with keys
  lineinfile: dest=/etc/ssh/sshd_config state=present regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"
  when: add_authorized_keys is success
  notify: sshd restart

